name: Build ImmortalWrt R66S

on:
  workflow_dispatch:
  push:
    branches:
      - v1.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch
        run: echo "workflow works on v1.0"
